---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    dnf:
      name: httpd
      state: absent
 
  - name: add php support for apache
    dnf:
      name: php
      state: absent

